export const ADD_REVIEW = "ADD_REVIEW";

export const REMOVE_REVIEW = "REMOVE_REVIEW";

export const EDIT_REVIEW = "EDIT_REVIEW";

export const SAVE_RESTAURANT = "SAVE_RESTAURANT";

export const REMOVE_RESTAURANT = "REMOVE_RESTAURANT";

